<h2>Tonder Form</h2>

<form action="#" id="tonder-test" method="POST">
    API URL:

    <input type="text" name="api_url" value="https://stage.tonder.io/api/v1/checkout-router/" style="width: 500px"> <br>

    Username:

    <input type="text" name="username" value="gacema@lyricspad.net" style="width: 500px"> <br>


    Password:

    <input type="text" name="password" value="HNNseypeNLB6vrd'" style="width: 500px"> <br>

    Body Data:

    <textarea type="textarea" name="body_data" rows="35" cols="50">{
  "card": {
    "skyflow_id": "09541643-4f26-455e-a462-734835a5ebad",
    "card_number": "2149-8690-2272-4430",
    "cardholder_name": "4c6847c4-6a2d-4d59-ac48-58aaf624d0ff",
    "cvv": "34aab0a2-01db-47b3-837f-6c83668ed46e",
    "expiration_month": "c4003819-fa74-4671-9a51-9157b19ae35a",
    "expiration_year": "9a503795-5ad8-4fde-8193-923fb5a0ecc2"
  },
  "name": "4c6847c4-6a2d-4d59-ac48-58aaf624d0ff",
  "last_name": "",
  "email_client": "test_user_7331827@testuser.com",
  "phone_number": "6666666666",
  "id_product": "no_id",
  "quantity_product": 1,
  "id_ship": "0",
  "instance_id_ship": "2",
  "amount": 91.97,
  "title_ship": "shipping",
  "description": "transaction",
  "device_session_id": "Az5fQZzK0UBrvA0XFosI76qFlJ6FQl8R",
  "token_id": "",
  "business_id": 47,
  "client_id": 337,
  "payment_id": 495
}</textarea> <br>
    <input type="submit" value="Submit">
</form>

<h1>Result:</h1>
<div id="result">

</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $('#tonder-test').on('submit', function () {
                $('#result').html('');
                var data = $('#tonder-test').serializeArray();
                var keyData = {};
                data.forEach(element => {keyData[element.name] = element.value});
                $.ajax({
                    url : '<?= $block->getUrl('tonder/payment/testpost') ?>',
                    data : keyData,
                    type : 'POST',
                    showLoader : true
                }).done(
                    function (response) {
                        $('#result').html(JSON.stringify(response));
                    }.bind(this)
                ).fail(
                    function () {
                        return false;
                    }
                );

                return false;
            });
        });
    })
</script>