<?php
/** Tonder */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
$scriptString = <<<script
require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'tonder'
            };
            layout([
                {
                    component: 'Tonder_Payment/js/view/payment/method-renderer/multishipping/'
                        + window.checkoutConfig.payment.tonder.connectionType,
                    name: 'payment_method_tonder',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<!-- ko template: getTemplate() --><!-- /ko -->

