<?php

/** @var Tonder\Payment\Block\Payment $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

?>

<?php
$scriptString = <<<script
require(
        [
            'Tonder_Moneris/js/moneris/direct',
            'jquery',
            'domReady!'
        ], function(Moneris, $) {
            var config = {$block->getPaymentConfig()},
                payment,
                form = $('#payment_form_{$block->getCode()}');

            config.active = form.length > 0 && !form.is(':hidden');
            payment = new Moneris(config);
        });
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>